GET http://localhost:3001/transactions

###

GET http://localhost:3001/transactions?page=2&perPage=10&search=Fjallraven


###

GET http://localhost:3001/statistics?month=2021-11

###

GET http://localhost:3001/bar-chart?month=2021-11


###

GET http://localhost:3001/pie-chart?month=2021-11


###

GET http://localhost:3001/combined-data